<a href="https://colab.research.google.com/github/ReutFarkash/TF_Keras_WU/blob/master/JH_3_2_Intro_to_tf_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2020 Version of Applications of Deep Neural Networks for TensorFlow and Keras (Washington University in St. Louis) - Jeff Heaton
Introduction to Tensorflow & Keras for Deep Learning with Python (3.2)

In [1]:
import tensorflow as tf
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 2.3.0


In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import numpy as np
from sklearn import metrics

In [4]:
df = pd.read_csv('http://data.heatonresearch.com/data/t81-558/auto-mpg.csv', na_values=['NA', '?'])
df.head()

mpg  cylinders  displacement  ...  year  origin                       name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino

[5 rows x 9 columns]

In [5]:
df.describe()

mpg   cylinders  ...        year      origin
count  398.000000  398.000000  ...  398.000000  398.000000
mean    23.514573    5.454774  ...   76.010050    1.572864
std      7.815984    1.701004  ...    3.697627    0.802055
min      9.000000    3.000000  ...   70.000000    1.000000
25%     17.500000    4.000000  ...   73.000000    1.000000
50%     23.000000    4.000000  ...   76.000000    1.000000
75%     29.000000    8.000000  ...   79.000000    2.000000
max     46.600000    8.000000  ...   82.000000    3.000000

[8 rows x 8 columns]

In [6]:
df.isnull().sum(axis=0)

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
year            0
origin          0
name            0
dtype: int64

In [9]:
cars = df['name']

# Handle missing values
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin']].values
y = df['mpg'].values

In [10]:
# Building the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu'))  # Hidden 1
model.add(Dense(10, activation='relu'))  # Hidden 2
model.add(Dense(1))  # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x, y, verbose=2, epochs=100)

Epoch 1/100
13/13 - 0s - loss: 63048.6133
Epoch 2/100
13/13 - 0s - loss: 2416.1064
Epoch 3/100
13/13 - 0s - loss: 2088.4011
Epoch 4/100
13/13 - 0s - loss: 1111.4209
Epoch 5/100
13/13 - 0s - loss: 801.9070
Epoch 6/100
13/13 - 0s - loss: 761.3662
Epoch 7/100
13/13 - 0s - loss: 719.3865
Epoch 8/100
13/13 - 0s - loss: 710.8268
Epoch 9/100
13/13 - 0s - loss: 697.0776
Epoch 10/100
13/13 - 0s - loss: 688.7709
Epoch 11/100
13/13 - 0s - loss: 677.4136
Epoch 12/100
13/13 - 0s - loss: 668.9657
Epoch 13/100
13/13 - 0s - loss: 658.6100
Epoch 14/100
13/13 - 0s - loss: 648.3344
Epoch 15/100
13/13 - 0s - loss: 637.5635
Epoch 16/100
13/13 - 0s - loss: 628.9115
Epoch 17/100
13/13 - 0s - loss: 617.4049
Epoch 18/100
13/13 - 0s - loss: 606.6071
Epoch 19/100
13/13 - 0s - loss: 594.9993
Epoch 20/100
13/13 - 0s - loss: 583.4478
Epoch 21/100
13/13 - 0s - loss: 575.6275
Epoch 22/100
13/13 - 0s - loss: 564.9742
Epoch 23/100
13/13 - 0s - loss: 552.1307
Epoch 24/100
13/13 - 0s - loss: 540.4130
Epoch 25/100
13/13 -

In [11]:
pred = model.predict(x)
print('Shape: {}'.format(pred.shape))
print(pred)

Shape: (398, 1)
[[16.228811 ]
 [16.254965 ]
 [16.51224  ]
 [17.472862 ]
 [16.805075 ]
 [15.029559 ]
 [14.808306 ]
 [15.155699 ]
 [15.37385  ]
 [15.4161215]
 [14.07583  ]
 [15.849958 ]
 [12.249499 ]
 [12.026043 ]
 [23.885828 ]
 [19.391752 ]
 [19.3091   ]
 [18.104507 ]
 [23.72762  ]
 [20.897505 ]
 [24.357254 ]
 [23.70713  ]
 [24.468393 ]
 [23.542267 ]
 [18.490671 ]
 [21.416138 ]
 [23.17061  ]
 [22.94909  ]
 [24.281733 ]
 [23.948343 ]
 [21.38832  ]
 [23.609898 ]
 [24.033487 ]
 [17.064808 ]
 [20.145689 ]
 [18.074867 ]
 [17.261385 ]
 [19.041498 ]
 [17.834023 ]
 [16.055231 ]
 [17.095964 ]
 [18.65629  ]
 [18.603466 ]
 [16.517769 ]
 [17.813715 ]
 [17.03061  ]
 [21.10738  ]
 [17.889072 ]
 [16.717222 ]
 [21.8939   ]
 [22.557423 ]
 [24.14038  ]
 [23.273376 ]
 [23.784744 ]
 [23.437382 ]
 [21.781134 ]
 [22.965666 ]
 [24.160446 ]
 [23.371462 ]
 [23.293531 ]
 [22.515358 ]
 [22.471008 ]
 [18.217222 ]
 [16.146683 ]
 [19.04271  ]
 [17.185907 ]
 [18.44345  ]
 [16.959282 ]
 [18.370476 ]
 [18.566383 ]
 [17

In [12]:
# Measure RMSE error
score = np.sqrt(metrics.mean_squared_error(pred, y))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 6.23828908477119


In [13]:
# Sample predictions
for i in range(10):
  print(f"{i+1}. Car: {cars[i]}, MPG: {y[i]}, predicted MPG: {pred[i]}")

1. Car: chevrolet chevelle malibu, MPG: 18.0, predicted MPG: [16.228811]
2. Car: buick skylark 320, MPG: 15.0, predicted MPG: [16.254965]
3. Car: plymouth satellite, MPG: 18.0, predicted MPG: [16.51224]
4. Car: amc rebel sst, MPG: 16.0, predicted MPG: [17.472862]
5. Car: ford torino, MPG: 17.0, predicted MPG: [16.805075]
6. Car: ford galaxie 500, MPG: 15.0, predicted MPG: [15.029559]
7. Car: chevrolet impala, MPG: 14.0, predicted MPG: [14.808306]
8. Car: plymouth fury iii, MPG: 14.0, predicted MPG: [15.155699]
9. Car: pontiac catalina, MPG: 14.0, predicted MPG: [15.37385]
10. Car: amc ambassador dpl, MPG: 15.0, predicted MPG: [15.4161215]


Simple Tesorflow Classification: Iris

In [15]:
from tensorflow.keras.callbacks import EarlyStopping

In [16]:
df = pd.read_csv('http://data.heatonresearch.com/data/t81-558/iris.csv', na_values=['NA', '?'])
df.head()

sepal_l  sepal_w  petal_l  petal_w      species
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [19]:
# Convert to numpy - Classification
x= df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species'])
species = dummies.columns
y = dummies.values

In [20]:
# Building the neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu'))  # Hidden 1
model.add(Dense(25, activation='relu'))  # Hidden 2
model.add(Dense(y.shape[1], activation='softmax'))  # Output
model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x, y, verbose=2, epochs=100)

Epoch 1/100
5/5 - 0s - loss: 1.0973
Epoch 2/100
5/5 - 0s - loss: 0.9209
Epoch 3/100
5/5 - 0s - loss: 0.8171
Epoch 4/100
5/5 - 0s - loss: 0.7488
Epoch 5/100
5/5 - 0s - loss: 0.6939
Epoch 6/100
5/5 - 0s - loss: 0.6421
Epoch 7/100
5/5 - 0s - loss: 0.6034
Epoch 8/100
5/5 - 0s - loss: 0.5691
Epoch 9/100
5/5 - 0s - loss: 0.5418
Epoch 10/100
5/5 - 0s - loss: 0.5140
Epoch 11/100
5/5 - 0s - loss: 0.4893
Epoch 12/100
5/5 - 0s - loss: 0.4680
Epoch 13/100
5/5 - 0s - loss: 0.4502
Epoch 14/100
5/5 - 0s - loss: 0.4301
Epoch 15/100
5/5 - 0s - loss: 0.4128
Epoch 16/100
5/5 - 0s - loss: 0.3987
Epoch 17/100
5/5 - 0s - loss: 0.3837
Epoch 18/100
5/5 - 0s - loss: 0.3696
Epoch 19/100
5/5 - 0s - loss: 0.3578
Epoch 20/100
5/5 - 0s - loss: 0.3444
Epoch 21/100
5/5 - 0s - loss: 0.3348
Epoch 22/100
5/5 - 0s - loss: 0.3210
Epoch 23/100
5/5 - 0s - loss: 0.3118
Epoch 24/100
5/5 - 0s - loss: 0.3007
Epoch 25/100
5/5 - 0s - loss: 0.2907
Epoch 26/100
5/5 - 0s - loss: 0.2789
Epoch 27/100
5/5 - 0s - loss: 0.2701
Epoch 28/1

In [21]:
print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [22]:
pred = model.predict(x)
print('Shape: {pred.shape}')
print(pred)

Shape: {pred.shape}
[[9.98215318e-01 1.78413314e-03 5.97703718e-07]
 [9.95041192e-01 4.95628919e-03 2.44418857e-06]
 [9.96899247e-01 3.09896073e-03 1.78676135e-06]
 [9.93709803e-01 6.28567906e-03 4.44451553e-06]
 [9.98399913e-01 1.59945805e-03 5.95097561e-07]
 [9.98255432e-01 1.74405333e-03 4.54228001e-07]
 [9.96865094e-01 3.13270651e-03 2.15141995e-06]
 [9.97271240e-01 2.72772182e-03 1.09506141e-06]
 [9.91927981e-01 8.06453638e-03 7.49660603e-06]
 [9.95342970e-01 4.65491926e-03 2.14034594e-06]
 [9.98713732e-01 1.28609699e-03 2.90521683e-07]
 [9.95966554e-01 4.03130706e-03 2.13009662e-06]
 [9.95349467e-01 4.64816205e-03 2.42624310e-06]
 [9.96579111e-01 3.41777527e-03 3.04748187e-06]
 [9.99634385e-01 3.65648768e-04 4.16846468e-08]
 [9.99586046e-01 4.13816539e-04 6.10957969e-08]
 [9.99208272e-01 7.91519706e-04 1.79566015e-07]
 [9.98015761e-01 1.98349706e-03 7.01741840e-07]
 [9.98447001e-01 1.55281124e-03 2.66107918e-07]
 [9.98560011e-01 1.43952749e-03 4.91542380e-07]
 [9.96240258e-01 3.7

In [23]:
np.set_printoptions(suppress=True)
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [25]:
predict_classes = np.argmax(pred, axis=1)
expected_classes = np.argmax(y, axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [26]:
print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [27]:
from sklearn.metrics import accuracy_score
correct = accuracy_score(expected_classes, predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.98


In [28]:
# ad hoc predictions:
sample_flower = np.array([[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict the {sample_flower} is: {species[pred]}")

[[0.00608942 0.2971945  0.696716  ]]
Predict the [[5. 3. 4. 2.]] is: Iris-virginica
